/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    "./app/**/*.{js,ts,jsx,tsx}",
    "./components/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "primary-container": "#ec6aff",
        "on-surface": "#ffffff",
        "surface-container-high": "#201f1f",
        "on-primary-fixed": "#000000",
        "surface-tint": "#f183ff",
        "on-tertiary-fixed-variant": "#6a6000",
        "surface": "#0e0e0e",
        "primary-dim": "#eb65ff",
        "secondary-dim": "#00d4ec",
        "on-background": "#ffffff",
        "secondary-container": "#006875",
        "inverse-surface": "#fcf9f8",
        "on-secondary": "#004d57",
        "on-primary-container": "#41004c",
        "on-secondary-container": "#e8fbff",
        "on-error-container": "#ffb2b9",
        "outline-variant": "#484847",
        "on-tertiary-fixed": "#4b4400",
        "primary-fixed": "#ec6aff",
        "surface-container-low": "#131313",
        "outline": "#767575",
        "tertiary": "#fff7d0",
        "on-secondary-fixed-variant": "#005964",
        "surface-container-highest": "#262626",
        "error": "#ff6e84",
        "surface-variant": "#262626",
        "secondary-fixed": "#26e6ff",
        "on-secondary-fixed": "#003a42",
        "on-primary": "#540062",
        "surface-container-lowest": "#000000",
        "surface-dim": "#0e0e0e",
        "inverse-primary": "#a300bc",
        "inverse-on-surface": "#565555",
        "on-tertiary": "#685e00",
        "error-container": "#a70138",
        "tertiary-dim": "#f0dc2b",
        "error-dim": "#d73357",
        "surface-bright": "#2c2c2c",
        "surface-container": "#1a1919",
        "tertiary-fixed-dim": "#f0dc2b",
        "on-tertiary-container": "#5f5600",
        "background": "#0e0e0e",
        "tertiary-container": "#ffeb3b",
        "on-error": "#490013",
        "on-surface-variant": "#adaaaa",
        "primary-fixed-dim": "#e64dff",
        "secondary-fixed-dim": "#00d7f0",
        "secondary": "#00e3fd",
        "tertiary-fixed": "#ffeb3b",
        "primary": "#f183ff",
        "on-primary-fixed-variant": "#50005e"
      },
      fontFamily: {
        "headline": ["Plus Jakarta Sans", "sans-serif"],
        "body": ["Manrope", "sans-serif"],
        "label": ["Manrope", "sans-serif"]
      },
      borderRadius: {"DEFAULT": "1rem", "lg": "2rem", "xl": "3rem", "full": "9999px"},
    },
  },
  plugins: [],
};
